server:
  port: 8765
spring:
  application:
    name: nacos-sentinel
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 47.107.152.93:8080
# 是对外暴露该服务信息
management:
  endpoints:
    web:
      exposure:
        include: '*'