server:
  port: 8762
spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
# 是对外暴露该服务信息
management:
  endpoints:
    web:
      exposure:
        include: '*'